### ISSUE TITLE
Prüfung Gültigkeit der Rechenoperation wird erst nach der Zahleneingabe durchgeführt

### ISSUE THREAD

**Issue by MichaelMrt03** [MichaelMrt03/TestRepo#34]
Wenn ich eine ungültige Zahl wie die 10 eingebe für die Auswahl der Rechenoperation wird man im nächsten Schritt dazu aufgefordert Zahl1 und danach Zahl2 einzugeben.
Erst danach erscheint die Meldung "Ungültige Eingabe..."

Die Meldung sollte schon erscheinen bevor irgendwelche Zahlen zum rechnen eingegeben werden können.

Bitte anpassen: @Mausklicker47 @ozi5700

**Comment by Azeiynali** [comment]
Ich habe dieses und einige andere Probleme gelöst und ein PR erstellt.
