### ISSUE TITLE
Fehler beim potenzieren

### ISSUE THREAD

**Issue by ProfNorm** [MichaelMrt03/TestRepo#42]
in der Kontrollstruktur steht potenzieren mit base und exponent als parameter. Es müssen aber num1 und num2 übergeben werden

**Comment by MichaelMrt03** [comment]
> habe den issue gelöst...werde pr in den main branch machen - der "taschenrechner" branch ist aber aktueller und der conflict ist dort auch schon gelöst. Was ist denn der main branch eig?

Guck mal oben im Issue Verlauf hatte da geschrieben Dividend und Divisor wäre lesbarer als jeweils immer num1+num2

**Comment by MichaelMrt03** [comment]
> gelöst - btw brauchte ich keinen confirm für den pr..ist das richtig?

Nein das ist nicht richtig. Das war möglich weil ich das Repository auf privat gestellt hatte damit nur wir das sehen, dann benötigt man aber anscheinend GitHub Enterprise wenn man Branches schützen will privat

**Comment by MichaelMrt03** [comment]
> Was ist denn der main branch eig?
main

Aber dieses Repo nutzen wir für alle möglichen Projekte einfach zum testen und damit wir nicht jedes mal ein neues Repository aufmachen müssen und alle immer wieder einladen und alle regeln usw. machen wir das ganze testen einfach hier. Und für den taschenrechner nutzen wir dann taschenrechner als main.

Wir haben einfach einen taschenrechner branch der unser main für taschenrechner ist. Wir können auch sowas wie main_php machen für einen php branch.

Das ist eigentlich ungewöhnlich und macht man nicht aber es geht ja ums testen.

**Comment by Mausklicker47** [comment]
> > habe den issue gelöst...werde pr in den main branch machen - der "taschenrechner" branch ist aber aktueller und der conflict ist dort auch schon gelöst. Was ist denn der main branch eig?
> 
> Guck mal oben im Issue Verlauf hatte da geschrieben Dividend und Divisor wäre lesbarer als jeweils immer num1+num2

es werden doch num1 und num2 durch eine eingabe übergeben

**Comment by MichaelMrt03** [comment]
Ja aber die Variablen von den Parametern der Funktion sind ja unabhängig davon.

Also da wo du die definierst im Kopf.

Beim Aufrufen der Methode muss man dann num1, num2 als Parameter übergeben aber in der Methode selber kann man ja andere Namen benutzen
